In [1]:
import sys
import numpy as np

In [5]:
print('Python Version: {}'.format(sys.version))
print('NumPy Version: {}'.format(np.__version__))

Python Version: 3.6.5 (default, Apr  4 2018, 15:09:05) 
[GCC 7.3.1 20180130 (Red Hat 7.3.1-2)]
NumPy Version: 1.12.1


In [6]:
# define scalar
x = 6
x

6

In [7]:
# define vector
x = np.array((1,2,3))
x

array([1, 2, 3])

In [11]:
# Get vector properties / characteristics
print('Vector x Dimensions: {}'.format(x.shape))
print('Vector x Size: {}'.format(x.size))

Vector x Dimensions: (3,)
Vector x Size: 3


In [15]:
# define a Matrix
x = np.matrix(([1,2,3],[4,5,6],[7,8,9]))

In [16]:
# Get Matrix properties / characteristics
print('Matrix x Dimensions: {}'.format(x.shape))
print('Matrix x Size: {}'.format(x.size))

Matrix x Dimensions: (3, 3)
Matrix x Size: 9


In [19]:
# define Matrix of any dimension
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [18]:
np.zeros((2,2))

array([[ 0.,  0.],
       [ 0.,  0.]])

In [21]:
# Tensors
np.ones((3,3,3))

array([[[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]])

In [23]:
# indexing
x = np.ones((5,5), dtype=int)
# note the difference btween x and print(x) - try it yourself
print(x)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
