# بسم الله الرحمن الرحيم

## Lecture - 02

### Continue - Linear Algebra Using Python Review

In [4]:
# Don't forget the imports - every session
import os
import numpy as np

In [6]:
# Quick way to create arrays - Interesting :)
x = np.array(range(9))
print(x)

[0 1 2 3 4 5 6 7 8]


In [10]:
# Don't forget to assign the output of the operation
x = x.reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [16]:
#Matrix Transpose
# Columns are flipped over the diagonal
xT = x.T
print(x.T)

[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [17]:
# Taking the Transpose of the Transpose will give us back the original array
print(xT.T)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [23]:
# Tensors
A = np.array((3,3,3,3,3,3,3,3,3,3))
print(A.shape)
print(len(A.shape))
print(A.size)

(10,)
1
10


### Diagonal Matrices
- Matrix is diagonal if $D_{i,j} = 0  \;\forall\; i \neq j$
- $\begin{bmatrix} 1 & 0 & 0\\ 0 & 2 & 0 \\ 0 & 0 & 3 \end{bmatrix}$
- Multiplying by diagonal matrix is computationally efficient
- For **diag(v)x**, we need to scale each $x_{i}$ by $v_{i}$, where $v_{i}$ is the diagonal element
- Some algorithms restrict their input parameter to be diagonal matrices, for efficiency
- Diagonal matrices don't need to be square

In [26]:
# Diagonal Matrices
# Generate the matrix in the same previous manner
x = np.arange(9).reshape((3,3))
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [27]:
# Diagonal Matrices - Continue
# Get the diagonal items values
np.diag(x)

array([0, 4, 8])

In [30]:
# Diagonal Matrices - Continue
# Generate the Diagonal Matrix from the previous values
print(np.diag(np.diag(x)))

#So, after this step, we generated a diagonal matrix based on another matrix using numpy

[[0 0 0]
 [0 4 0]
 [0 0 8]]


### Symmetric Matrices
- Matrix that is equal to its Transpose
- **A = $A^{T}$**
- $\begin{bmatrix} 1 & 2 & 3\\ 2 & 3 & 4 \\ 3 & 4 & 5 \end{bmatrix}$
- Such matrices exists when the entries are generated by functions that are similar from both sides
  - example: if this matrix holds distances between points(i,j) - d(i,j) = d(j,i)
  - Usually, Euclidean distances are symmetric

In [32]:
# Symmetric Matrices Example
a = np.array(([1,2,3],[2,3,4],[3,4,5]))
np.allclose(a, a.T)

True

In [35]:
# Another Symmetric Matrices Example
a = np.array(np.arange(9).reshape(3,3))
np.allclose(a, a.T)

False

### The Unit Vector
- Vector with unit norm
- $\left\lVert x\right\rVert _{2} = 1$
  - L2 norm
  - also known as Euclidean norm; not recommended name
  - also known as *magnitude*
  - Cartesian distance from origin
  - $\sqrt{\sum x_{i}^{2}}\;\forall\;_{i}\;in \;X$
- Unit vector can be obtained by normalizing any vector

### Vector Normalization
- The process of dividing a vector by its magnitude, which produces a unit vector
- $\frac{X}{\left\lVert x\right\rVert _{2}}$ = unit vector
- Dividing the vector by its magnitude gives us the unit vector
- Common preprocessing step
- Example
  - $x = \begin{bmatrix} 1 & 1 & 1 & 1 \end{bmatrix}$
  - $\frac{x}{\sqrt{4}} = \begin{bmatrix} 1/2 & 1/2 & 1/2 & 1/2 \end{bmatrix}$
  - This vector has magnitude of 1, so it is a unit vector
 

In [44]:
# Getting Vector Norm Example
from numpy import linalg as LA

# Types of supported norms
# ord 	norm for matrices 	norm for vectors
# None 	Frobenius norm 	2-norm
# ‘fro’ 	Frobenius norm 	–
# ‘nuc’ 	nuclear norm 	–
# inf 	max(sum(abs(x), axis=1)) 	max(abs(x))
# -inf 	min(sum(abs(x), axis=1)) 	min(abs(x))
# 0 	– 	sum(x != 0)
# 1 	max(sum(abs(x), axis=0)) 	as below
# -1 	min(sum(abs(x), axis=0)) 	as below
# 2 	2-norm (largest sing. value) 	as below
# -2 	smallest singular value 	as below
# other 	– 	sum(abs(x)**ord)**(1./ord)

a = np.ones(4, dtype=int)
# print(a)
LA.norm(a)

2.0

In [49]:
# Matrix Normalization Example
# The intuition for normalizing the vectors is that elements within the vector that have large magnitudes may not be more important, 
# so normalizing them puts all elements roughly in the same scale.
# Note, we are using sklearn package here
# sudo pip install -U scikit-learn

from sklearn import preprocessing
 
# Two samples, with 3 dimensions.
# The 2 rows indicate 2 samples, 
# and the 3 columns indicate 3 features for each sample.
X = np.asarray([[-1,0,1],
                [0,1,2]], dtype=np.float) # Float is needed.
 
# Before-normalization.
print(X)

[[-1.  0.  1.]
 [ 0.  1.  2.]]


In [50]:
# Symmetric Matrices Example
# l2-normalize the samples (rows). 
X_normalized = preprocessing.normalize(X, norm='l2')
 
# After normalization.
print(X_normalized)

[[-0.70710678  0.          0.70710678]
 [ 0.          0.4472136   0.89442719]]


### Orthogonality
- vector $x$ and vector $y$ are orthogonal to each other if $x^{T}y = 0$
- If two vectors are orthogonal and both have a nonzero magnitude, they will be at a 90 degree angle to each other
- If two vectors are orthogonal and unit vectors, they are called orthonormal
- ![](imgs/Lecture-02/arrowperp.png)

In [52]:
# Symmetric Matrices Example

## Eigen Decomposition
- breaking mathematical objects into their constituent parts
- mathematical objects can be understood better when they are broken into their constituetional parts
  - integers could be decomposed into prime factors
  - As 10 = 2 * 5, 
    - 10 is not divisible by 3
    - any integer that is multiple by 10, is also divisible by 5
- We can decompose matrices in ways that reveals information about their functional properties that is not immediately obvious from the representation of the matrix as an array of elements
- Matrix, can be represented as
  - Eigenvectors
  - Eigenvalues

### Eigen Vectors and Eigenvalues
- Eigenvector of a square matrix $A$ is a nonzero vector $v$ such that multiplication by $A$ alters only the scale of $v$
- $A v = \lambda v$
- This is called: Eigenvalue equation
- $v$ - the eigenvector
- $\lambda$ - a scalar, the eigenvalue corresponding to $v$
- Eigenvector is used to longee or shirnk the matrix
- ![](imgs/Lecture-02/eigen.png)
- Figure shows the effect of Multiplication of the two orthonormal eigenvectors $^{1}$ and $^{2}$ by the matrix $A$ that lead to the distort of the unit circle